name: Dart CI

on:
  push:
    branches: [ release/apk ]
  pull_request:
    branches: [ release/apk ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: oursky/flutter:v1.12.13-hotfix.5

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter pub run test
    - name : Generate APK
      run: flutter build apk --obfuscate --split-debug-info="SplitDebugInfo"
